config/routes.rb
Rails.application.routes.draw do

  get 'inventories/index'
  get 'inventories/show'
  get 'inventories/new'
  get 'inventories/edit'
  get 'inventories/create'
  resources :inventories

  root 'inventories#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/integration.rb
require 'rest_client'
require 'json'
class Integration
  attr_accessor :create_url, :update_url

  def initialize(user)
    @user = user
    @webhook = @user.webhook
    @create_url = @webhook.create_url
    @update_url = @webhook.update_url
  end

  def push(payload = nil, type)
    begin
      header = {'content_Type' => 'application/json'}
      payload = payload
      url = (type == 'create') ? @create_url : @update_url
      response = RestClient::Request.execute(method: :post, url: url, payload: payload, header: header)
      if [200,400].include?(response.code)
        return true
      else
        puts "Response:: Body::#{response.body}"
        return response
      end
    rescue Exception => e
      puts "Error::Integration::PushInv::Message:: #{e.message}"
    end
    
  end


end 

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  after_create :push_after_create
  after_update :push_after_update
  validates :sku, presence: true, length: { minimum: 2 }
  validates :price, presence: true

  def push_after_update
    inventory = self
    user = inventory.user
    payload = inventory.to_json
    response = Integration.new(user).push(payload, "update")
    puts response
    return true
  end

  def push_after_create
    inventory = self
    user = inventory.user
    payload = inventory.to_json
    response = Integration.new(user).push(payload, "create")
    puts response
    return true
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :inventories, dependent: :destroy
	has_one :webhook, dependent: :destroy
end

app/models/webhook.rb
class Webhook < ApplicationRecord
  belongs_to :user
  scope :active, -> {where(status: ture)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def edit
   @inventories = Inventory.find(params[:id])
  end

  def update
    inventory = Inventory.find(params[:id])
    inventory.update(inv_params)
    redirect_to root_path
  end

  def index
    @inventories = Inventory.where(user_id:1)
  end

  def create
    @inventory = Inventory.new(inv_params)
    @inventory.user_id = 1 #this only for time being aadded
    if @inventory.save
      redirect_to @inventory
    else
      render 'new'
    end
  end

  private

  def inv_params
    params.require(:inventory).permit(:sku, :price, :quntity, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/edit.html.erb
<h1>Inventories - Update</h1>
<%= form_with(model: @inventories, local: true) do |form| %>
  <p>
    <%= form.label :sku %><br>
    <%= form.text_field :sku %>
  </p>
 
  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>

  <p>
    <%= form.label :quntity %><br>
    <%= form.text_field :quntity %>
  </p>

  <p>
    <%= form.label :user_id %><br>
    <%= form.text_field :user_id %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>


<p>
	<%= link_to 'Back', root_path %>
</p>

app/views/inventories/index.html.erb
<h1>Inventory</h1>

<h2><%= link_to 'Create', new_inventory_path %></h2>
 
<table>
  <tr>
    <th>SKU</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
 
  <% @inventories.each do |inventory| %>
    <tr>
      <td><%= inventory.sku %></td>
      <td><%= inventory.price %></td>
      <td><%= inventory.quntity %></td>
      <td><%= link_to 'Show', inventory_path(inventory) %></td>
      <td><%= link_to 'Edit', edit_inventory_path(inventory.id) %></td>
    </tr>
  <% end %>
</table>

app/views/inventories/new.html.erb
<h1>Inventories - new</h1>
<% if @inventory.errors.any? %>
  <h3>The following errors prevented the inventory from being saved:</h3>
  <ul>
    <% @inventory.errors.full_messages.each do |msg| %>
     <li><%= msg %></li> 
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :inventory, url: inventories_path, local: true do |form| %>

  <p>
    <%= form.label :sku %><br>
    <%= form.text_field :sku %>
  </p>
 
  <p>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </p>

  <p>
    <%= form.label :quntity %><br>
    <%= form.number_field :quntity %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/inventories/show.html.erb
<h1>Inventories#show</h1>


<p>
  <strong>SKU:</strong>
  <%= @inventory.sku %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @inventory.price%>
</p>

<p>
  <strong>Qty:</strong>
  <%= @inventory.quntity%>
</p>

<p>
	<%= link_to 'Back', root_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebhookApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>